# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DealerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('batch_no', models.IntegerField(unique=True)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('org_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('margin_price', models.DecimalField(decimal_places=5, default=0, max_digits=5, null=True)),
                ('description', models.CharField(max_length=200)),
                ('present_stock', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.DealerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dealerdetails',
            name='get_dealer_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.PersonDetails'),
        ),
        migrations.AddField(
            model_name='customerdetais',
            name='get_dist_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP.PersonDetails'),
        ),
    ]
